//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fatiao.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 执行次数 {
            get {
                return ((string)(this["执行次数"]));
            }
            set {
                this["执行次数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl + F10")]
        public string 运行快捷键 {
            get {
                return ((string)(this["运行快捷键"]));
            }
            set {
                this["运行快捷键"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl + F11")]
        public string 暂停快捷键 {
            get {
                return ((string)(this["暂停快捷键"]));
            }
            set {
                this["暂停快捷键"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl + F12")]
        public string 调试快捷键 {
            get {
                return ((string)(this["调试快捷键"]));
            }
            set {
                this["调试快捷键"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 开机自启动 {
            get {
                return ((bool)(this["开机自启动"]));
            }
            set {
                this["开机自启动"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 最小化启动 {
            get {
                return ((bool)(this["最小化启动"]));
            }
            set {
                this["最小化启动"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("音量减")]
        public string 触边滚轮1 {
            get {
                return ((string)(this["触边滚轮1"]));
            }
            set {
                this["触边滚轮1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("音量加")]
        public string 触边滚轮2 {
            get {
                return ((string)(this["触边滚轮2"]));
            }
            set {
                this["触边滚轮2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("静音")]
        public string 触边滚轮3 {
            get {
                return ((string)(this["触边滚轮3"]));
            }
            set {
                this["触边滚轮3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮4 {
            get {
                return ((string)(this["触边滚轮4"]));
            }
            set {
                this["触边滚轮4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮5 {
            get {
                return ((string)(this["触边滚轮5"]));
            }
            set {
                this["触边滚轮5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮6 {
            get {
                return ((string)(this["触边滚轮6"]));
            }
            set {
                this["触边滚轮6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮7 {
            get {
                return ((string)(this["触边滚轮7"]));
            }
            set {
                this["触边滚轮7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮8 {
            get {
                return ((string)(this["触边滚轮8"]));
            }
            set {
                this["触边滚轮8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮9 {
            get {
                return ((string)(this["触边滚轮9"]));
            }
            set {
                this["触边滚轮9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮10 {
            get {
                return ((string)(this["触边滚轮10"]));
            }
            set {
                this["触边滚轮10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮11 {
            get {
                return ((string)(this["触边滚轮11"]));
            }
            set {
                this["触边滚轮11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无")]
        public string 触边滚轮12 {
            get {
                return ((string)(this["触边滚轮12"]));
            }
            set {
                this["触边滚轮12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 运行完成勾选 {
            get {
                return ((bool)(this["运行完成勾选"]));
            }
            set {
                this["运行完成勾选"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("鼠标中键")]
        public string 鼠标面板 {
            get {
                return ((string)(this["鼠标面板"]));
            }
            set {
                this["鼠标面板"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 启用面板 {
            get {
                return ((bool)(this["启用面板"]));
            }
            set {
                this["启用面板"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("打开资源管理器")]
        public string 轮盘上 {
            get {
                return ((string)(this["轮盘上"]));
            }
            set {
                this["轮盘上"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新建记事本")]
        public string 轮盘下 {
            get {
                return ((string)(this["轮盘下"]));
            }
            set {
                this["轮盘下"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Emoji表情")]
        public string 轮盘左 {
            get {
                return ((string)(this["轮盘左"]));
            }
            set {
                this["轮盘左"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("截图到剪贴板")]
        public string 轮盘右 {
            get {
                return ((string)(this["轮盘右"]));
            }
            set {
                this["轮盘右"] = value;
            }
        }
    }
}
